[package]
edition.workspace = true
name = "fc-gpui-sum-tree"
version = "0.5.1"
publish = true
description = "A sum tree data structure, a concurrency-friendly B-tree (originally from Zed - github.com/zed-industries/zed)"
authors.workspace = true
repository.workspace = true
readme = false
license.workspace = true

[lib]
name = "adabraka_sum_tree"
path = "src/sum_tree.rs"
doctest = false

[dependencies.arrayvec]
version = "0.7.1"

[dependencies]
log.workspace = true

[dependencies.rayon]
version = "1.8"


[dev-dependencies]
ctor = "1.0.13"
env_logger.workspace = true
rand.workspace = true

[lints.clippy]
dbg_macro = "deny"
declare_interior_mutable_const = "deny"
disallowed_methods = "deny"
large_enum_variant = "allow"
let_underscore_future = "allow"
nonminimal_bool = "allow"
redundant_clone = "deny"
single_range_in_vec_init = "allow"
todo = "deny"
too_many_arguments = "allow"
type_complexity = "allow"

[lints.clippy.style]
level = "allow"
priority = -1

[lints.rust.unexpected_cfgs]
level = "allow"
priority = 0
